# 06 — Pandas Data Wrangling

## Learning goals
- Create DataFrames
- Clean/filter/sort data
- Group and aggregate

In [10]:
import pandas as pd

data = {
    "name": ["Amina", "Brian", "Chao", "Dina", "Eli"],
    "score": [88, 72, 95, 67, 81],
    "hours": [10, 7, 12, 5, 9],
}

df = pd.DataFrame(data)
df

    name  score  hours
0  Amina     88     10
1  Brian     72      7
2   Chao     95     12
3   Dina     67      5
4    Eli     81      9

In [11]:
# Filter and derive columns
filtered = df[df["score"] >= 80].copy()
filtered["efficiency"] = filtered["score"] / filtered["hours"]
filtered.sort_values("efficiency", ascending=False)

    name  score  hours  efficiency
4    Eli     81      9    9.000000
0  Amina     88     10    8.800000
2   Chao     95     12    7.916667

In [12]:
bins = pd.cut(df["hours"], bins=[0, 6, 9, 12], labels=["low", "mid", "high"])
# Set observed=False to retain current behavior
grouped = df.groupby(bins, observed=False)["score"].mean()

print(grouped)

hours
low     67.0
mid     76.5
high    91.5
Name: score, dtype: float64

In [13]:
# Practice task:
# Add a pass/fail column where pass is score >= 75.

In [14]:
import pandas as pd

# Original data
data = {
    "name": ["Amina", "Brian", "Chao", "Dina", "Eli"],
    "score": [88, 72, 95, 67, 81],
    "hours": [10, 7, 12, 5, 9],
}

df = pd.DataFrame(data)

# Add a pass/fail column
df["pass"] = df["score"] >= 75  # True if score >= 75, else False

# Print the updated DataFrame
print(df)

    name  score  hours   pass
0  Amina     88     10   True
1  Brian     72      7  False
2   Chao     95     12   True
3   Dina     67      5  False
4    Eli     81      9   True